Quinte dev branch
UEA-advanced-programmers/C_Flat pull request #13
Opened 2022-11-13 19:01 UTC by Quilver

If and While statements

2022-11-13 21:44 UTC, A-Russell23 requested changes
This is a good start. I've left a few comments about some things that need a look over. If you could sort them out that would be great. If you don't agree or you're not sure what I mean, I'm happy to have a discussion with you and/or the team.

A couple notes...

Just for future reference, its great that you've implemented while loops but it would have been better for you to finish up all of your assigned work (such as unit tests) before branching out to other things. If you had put that extra time into getting tests to work, this might have been ready to merge on Monday. I'd say its always better to have a working project with less functionality rather than a broken project with more functionality. Its also worth noting that the longer it takes to get stuff merged, the more conflicts are likely to happen once we are able to merge this work, so this should always be a priority. Don't forget to think about how your actions might affect the wider team and the project as a whole :)

Another quick note, for `ParserUnit.cs` you'll need to add tests for the rest of the code, not just for the if/else statements you've added. You also need to include tests for errors.

2022-11-13 21:44 UTC, A-Russell23 commented on C_Flat_Interpreter/Parser/Parser.cs
> +			if (CheckElse())
`CheckElse` could be added to line 364, like you've done on line 337

2022-11-13 21:44 UTC, A-Russell23 commented on C_Flat_Interpreter/Parser/Parser.cs
> +			SubBlock(level + 1);
Ensure `subblock` is only called if `CheckElse` returns true

2022-11-17 16:48 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +	private void PrintCurrentLevel()
Removed

2022-11-17 16:50 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +			SubBlock(level + 1);
Got it

2022-11-17 16:52 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +			if (CheckElse())
Got it

2022-11-17 16:52 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +	Stack<int> tokenIndexStack;
Removed

2022-11-19 14:32 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +	private void Block(int level)
I'll move it down for now, but we should discuss implementation of multiple lines of code

2022-11-19 14:40 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +		if (Match(TokenType.String) && CheckIf())
I'm not sure what you mean by this

2022-11-19 14:42 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +	private void SubBlock(int level) {
I prefer having smaller functions. Although perhaps I had an issue with poorly naming the functions

2022-11-22 11:20 UTC, KThompson-Lane commented
Closing as this is was superseded by #14

2022-11-22 11:20 UTC, closed without merging