Quinte old code
UEA-advanced-programmers/C_Flat pull request #14
Opened 2022-11-19 14:58 UTC by Quilver

This is the updated version of the code from last week with changes as recommended from the code review.
I also took the liberty of rewriting my parser unit tests using the Lexer to tokenise test examples to see if they are working correctly.

2022-11-20 13:22 UTC, A-Russell23 requested changes

2022-11-20 13:22 UTC, A-Russell23 commented on C_Flat_Tests/Tests_Unit/ParserUnit.cs
> +        Lexer lexer = new Lexer();
You shouldn't be using lexer in the parser unit tests. The point of unit tests is to test individual sections of code in isolation so you know that section of code is the problem if the test fails. By using the lexer in the parser unit tests, you don't know if the problem is originating from the lexer or the parser.

Please don't forget to read our docs. This was writting in Testing.md -
' As these are Unit tests they should only test the code within that class. I.e. ExecutionUnit.cs should not rely on Lexer or Parser only Execution.'

2022-11-20 13:22 UTC, A-Russell23 commented on C_Flat_Tests/Tests_Unit/ParserUnit.cs
> +        Lexer lexer = new Lexer();
You shouldn't be using lexer in the parser unit tests

2022-11-20 13:22 UTC, A-Russell23 commented on C_Flat_Tests/Tests_Unit/ParserUnit.cs
> +        Lexer lexer = new Lexer();
You shouldn't be using lexer in the parser unit tests

2022-11-20 13:22 UTC, A-Russell23 commented on C_Flat_Tests/Tests_Unit/ParserUnit.cs
> +        Lexer lexer = new Lexer();
You shouldn't be using lexer in the parser unit tests

2022-11-20 13:22 UTC, A-Russell23 commented on C_Flat_Tests/Tests_Unit/ParserUnit.cs
> +        Lexer lexer = new Lexer();
You shouldn't be using lexer in the parser unit tests

2022-11-21 11:17 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +	private void BlockInternals(int level)
When writing block internals I was thinking this could be reused to parse multiline statements for the parser in general. We probably need to discuss how we are going to handle multi line statements in the parser in the group

2022-11-21 11:25 UTC, Quilver commented
I wanted to ask if I had a sufficient number of tests. In particular do I need to test for exceptions for improper syntax.

2022-11-21 11:28 UTC, Quilver commented on C_Flat_Interpreter/Parser/Parser.cs
> +	Stack<int> tokenIndexStack;
I think I should probably remove this variable along with the set function. I use them to stop the statement code from resetting to index to 0 after failed parse attempt. I could just directly reset things after each catch

2022-11-21 11:32 UTC, Quilver commented
Just want to state that the main issues were:
1. naming inconsistent with conventions that are laid out
2. using lexer in parser unit tests
3. semicolons testing (EBNF changes)
4. Division between Block and BlockInternals (I would like to discuss this)

2022-11-22 11:11 UTC, KThompson-Lane commented
Couple notes:
1. This code is still broken, it has inconsistent errors regarding logical statements and expressions within logic expressions such as `(10 + 100) < 10` 
2. Nobody assigned you to do the "try statement" work. Not only was it not currently necessary, it has introduced further complexity resulting in errors throughout the code and your use of it is not even consistent. (See `Statement()`) 
3. We explicitly told you to remove the dependency on Lexer from the parser unit tests. You completely ignored this and chose to leave it in, without giving a reason as to why in your PR or any other communications. It completely invalidates the purpose of the "unit test" when you rely on another unit of code for your testing. This was made explicitly clear in both meetings and the testing documentation I'll assume you still have not read. 
4. You've left in "set" but you haven't modified "reset" to use it. Is this intentional? Because you've included zero comments throughout explaining your intentions.
5. All of your functions do not match the EBNF naming convention, nor are they even a correct implementation of those EBNF definitions. If you felt that the EBNF was incorrect, you should have voiced that instead of silently changing the code such that it does not match the definition.

Frankly this code **should not** be allowed to merge, however, as we are now so close to the deadline, we have no choice but to allow this to be merged for either myself or Alexandra to then spend our own time fixing and refactoring it to a point where it is satisfactory. 

All of these issues could have been avoided through communication, we have a teams channel, if you feel that you disagree with work you have decided to implement, or disagree with choices made as a group in the lab then voice those to us. Please do not instead stay quiet and just do what you feel is right. This is as of right now your sole contribution to the code-base and it will require further work to even bring it to a point it should have been 2 weeks ago.

2022-11-22 11:19 UTC, KThompson-Lane approved these changes

2022-11-22 19:38 UTC, merged