Update documentation
UEA-advanced-programmers/C_Flat pull request #16
Opened 2022-11-20 16:41 UTC by A-Russell23

## Changes:

- A few minor fixes to the EBNF
- Added an explanation of our syntax with examples. I've marked which sections are in progress/not implemented yet. This should be updated as required.

2022-11-21 13:13 UTC, Spartan-Bailey requested changes

2022-11-21 13:13 UTC, Spartan-Bailey commented on C_Flat Definition.md
> -`<Keyword>::= 'if' || 'else' || 'while' || 'var' || 'func' | 'true' | 'false`
quotation on false keyword is not complete

2022-11-21 13:13 UTC, Spartan-Bailey commented on C_Flat Definition.md
>  `<Assignment>::= <Identifier> '=' (<Expression> | ' " '<Word>' " ' | <Logic-Statement>) ‘;’`
Semi colon needs to be removed from Assignment as it is already covered in Declaration

2022-11-21 13:13 UTC, Spartan-Bailey commented on C_Flat Definition.md
>  `<Assignment>::= <Identifier> '=' (<Expression> | ' " '<Word>' " ' | <Logic-Statement>) ‘;’`
Assignment needs to be put on a new line

2022-11-22 11:28 UTC, A-Russell23 commented on C_Flat Definition.md
>  `<Assignment>::= <Identifier> '=' (<Expression> | ' " '<Word>' " ' | <Logic-Statement>) ‘;’`
There was an issue with duplicate semi-colons but I've fixed this here by adding the semi-colon after Identifier in Declaration, and keeping it as part of Assignment. So this should all be correct. Hopefully that makes sense!

Just to note, as I think you might have gotten confused here - anything highlighted in red is whats been removed and anything highlighted in green is whats been added/changed. :)

2022-11-22 11:28 UTC, A-Russell23 commented on C_Flat Definition.md
>  `<Assignment>::= <Identifier> '=' (<Expression> | ' " '<Word>' " ' | <Logic-Statement>) ‘;’`
Yep thats been done here in this change :)

2022-11-22 11:28 UTC, A-Russell23 commented on C_Flat Definition.md
> -`<Keyword>::= 'if' || 'else' || 'while' || 'var' || 'func' | 'true' | 'false`
Thanks for letting me know, I'll fix this now :)

2022-11-28 12:05 UTC, Spartan-Bailey approved these changes

2022-11-28 12:05 UTC, merged